### ISSUE TITLE
exoplayer crash and exit app automatically

### ISSUE THREAD

**Issue by advado** [khaled-0/LeanStream#2]
exoplayer crash or exit app in a new commit, please fix

**Comment by khaled-0** [comment]
Fixed!

**Comment by khaled-0** [comment]
still happening on mobile device

**Comment by advado** [comment]
great job!! good work, keep it up..

please fix the search result.  and display density 240 problems, 320 density UI is OK, but if I change density to 240 then UI also changes.

**Comment by khaled-0** [comment]
> great job!! good work, keep it up..
> 
> please fix the search result. and display density 240 problems, 320 density UI is OK, but if I change density to 240 then UI also changes.

What about the search result? I don't see the issue

**Comment by advado** [comment]
> > great job!! good work, keep it up..
> > please fix the search result. and display density 240 problems, 320 density UI is OK, but if I change density to 240 then UI also changes.
> 
> What about the search result? I don't see the issue

search result is fixed. working now..

**Comment by khaled-0** [comment]
> great job!! good work, keep it up..
> 
> and display density 240 problems, 320 density UI is OK, but if I change density to 240 then UI also changes.

Replaced filter chip with buttons for tv, idk it seems fine to me
