### ISSUE TITLE
search result not get properly 

### ISSUE THREAD

**Issue by advado** [khaled-0/LeanStream#3]
hey bro, the search not getting results properly.  Is it possible to get results by searching the "tvg-name=" from .m3u list, for more accuracy?.

please also add the channel logo and title at the bottom of the player, and hide automatically after few seconds.

**Comment by khaled-0** [comment]
the search is currently case sensitive, that's probably why, I'll fix it soon

**Comment by advado** [comment]
The search is working well now, bro you are a great coder.

bro, please enable ".mpd" DASH url support in Exoplayer,  because new m3u files have both types of URLs  .mpd and .m3u8

**Comment by khaled-0** [comment]
.mpd links already works it seems
 tested with
https://vs-cmaf-pushb-ww-live.akamaized.net/x=4/i=urn:bbc:pips:service:bbc_arabic_tv/pc_hd_abr_v2.mpd

**Comment by khaled-0** [comment]
https://github.com/khaled-0/LeanStream/commit/16518e6572b27257714572a2855557f2de230b79
