### ISSUE TITLE
Screenshot?

### ISSUE THREAD

**Issue by lars18th** [khaled-0/LeanStream#4]
Hi,

I suggest to add some screenshot of the App.

Thank you.

**Comment by khaled-0** [comment]
There's not much in the app at this moment
 I'm planning to add some after adding a few more stuffs soon
But here you go

![Screenshot_20240305-233428_Pixel Launcher](https://github.com/khaled-0/LeanStream/assets/74397286/c4a20d00-cdc4-46cd-b4b3-da5b16a9dee7)
![Screenshot_20240305-233340_Pixel Launcher](https://github.com/khaled-0/LeanStream/assets/74397286/76d5ef3f-ada5-4933-b350-188f2ce51349)

**Comment by lars18th** [comment]
Thank you.

**Comment by khaled-0** [comment]
https://github.com/khaled-0/LeanStream/commit/ff9d3ab4e77849c721370fd6fbb13d8f6fd501e3
