### ISSUE TITLE
dislay density issues

### ISSUE THREAD

**Issue by advado** [khaled-0/LeanStream#5]
hey bro,  great app working perfectly.. your code is working fine on 320 density

please fix display density isuue,  most of 90 percent  devices  working  on 240 density..  if i install app on 240 density based devices, channel logos and top category tab is very hard to visible from noramal distance.. 

change density via android studio terminal and please check once .    :   "adb shell wm density 240"

**Comment by khaled-0** [comment]
> hey bro, great app working perfectly.. your code is working fine on 320 density
> 
> please fix display density isuue, most of 90 percent devices working on 240 density.. if i install app on 240 density based devices, channel logos and top category tab is very hard to visible from noramal distance..
> 
> change density via android studio terminal and please check once . : "adb shell wm density 240"

here's the thing
 I don't know what should I do for large screen.
Should I just make the ui bigger?
Please give suggestions

**Comment by advado** [comment]
run the app in android studio emulator.  and apply adb command in studio emulator..   adb command is : "adb shell wm density 240"

then use can see the problem, please check  the below images.  before and after change density


![Screenshot_20240313_195420](https://github.com/khaled-0/LeanStream/assets/53028392/5ed1e957-90fe-4d9f-b4b7-010cc33dbb21)
![Screenshot_20240313_195402](https://github.com/khaled-0/LeanStream/assets/53028392/1b2a2e7c-61c3-4397-b567-a25d78b32629)
![Screenshot 2024-03-13 195056](https://github.com/khaled-0/LeanStream/assets/53028392/9aba239d-7c2f-4689-bb09-c469d5a7e292)

**Comment by khaled-0** [comment]
Updated 
Looks much better now imo
