### ISSUE TITLE
.ts format not support

### ISSUE THREAD

**Issue by advado** [khaled-0/LeanStream#7]
hey bro,  app is great but .ts stream format not support. bacause all new iptv app have support .ts type

check following file.. includs all type format
https://github.com/imdhiru/bloginstall-iptv/blob/main/bloginstall-iptv.m3u

**Comment by khaled-0** [comment]
https://github.com/google/ExoPlayer/issues/7560

**Comment by khaled-0** [comment]
That took a long time.
Please try the latest snapshot build
